CREATE TABLE EMPLOYEES
AS SELECT * FROM HR.EMPLOYEES;

SELECT * FROM USER1.EMPLOYEES;

DELETE from EMPLOYEES;
ROLLBACK;
UPDATE EMPLOYEES set first_name = 'a';
COMMIT;
ROLLBACK;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (100, 110);

UPDATE EMPLOYEES -- início da transação
SET SALARY = SALARY - 1000
WHERE EMPLOYEE_ID = 100;

UPDATE EMPLOYEES
SET SALARY = SALARY + 1000
WHERE EMPLOYEE_ID = 110;

