CREATE DATABASE TechnicalAssistance;

USE TechnicalAssistance;

CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CODE INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL
);