DROP TABLE manutencao;
DROP TABLE passageiro_voo;
DROP TABLE funcionario_voo;
DROP TABLE voo;
DROP TABLE aeroporto;
DROP TABLE funcionario;
DROP TABLE passageiro;
DROP TABLE aeronave;


-- Tabela de Aeronaves
CREATE TABLE aeronave (
   aeronave_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   modelo        VARCHAR(100) NOT NULL,
   fabricante    VARCHAR(100) NOT NULL,
   capacidade    NUMBER NOT NULL,
   status        VARCHAR(50) NOT NULL
);

-- Tabela de Passageiros
CREATE TABLE passageiro (
   passageiro_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nome          VARCHAR(50) NOT NULL,
   cpf           VARCHAR(11) NOT NULL UNIQUE,
   telefone      VARCHAR(15) NOT NULL,
   passaporte    VARCHAR(50)
);

-- Tabela de Funcionários
CREATE TABLE funcionario (
   funcionario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nome           VARCHAR(50) NOT NULL,
   cpf            VARCHAR(11) NOT NULL UNIQUE,
   cargo          VARCHAR(50) NOT NULL,
   setor          VARCHAR(50) NOT NULL
);

-- Tabela de Aeroportos
CREATE TABLE aeroporto (
   aeroporto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nome         VARCHAR(50) NOT NULL,
   cidade       VARCHAR(50) NOT NULL,
   estado       VARCHAR(50) NOT NULL,
   pais         VARCHAR(50) NOT NULL
);

-- Tabela de Voos
CREATE TABLE voo (
   voo_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   numero_voo    VARCHAR(50) NOT NULL,
   aeronave_id   NUMBER NOT NULL,
   destino_id    NUMBER NOT NULL,
   origem_id     NUMBER NOT NULL,
   data_partida  DATE NOT NULL,
   data_chegada  DATE NOT NULL,
   status        NUMBER NOT NULL,
   CONSTRAINT fk_aeronave FOREIGN KEY (aeronave_id) REFERENCES aeronave (aeronave_id),
   CONSTRAINT fk_destino FOREIGN KEY (destino_id) REFERENCES aeroporto (aeroporto_id),
   CONSTRAINT fk_origem FOREIGN KEY (origem_id) REFERENCES aeroporto (aeroporto_id)
);

-- Tabela de Funcionários por Voo
CREATE TABLE funcionario_voo (
   funcionario_voo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   funcionario_id     NUMBER NOT NULL,
   voo_id             NUMBER NOT NULL,
   cargo_funcionario  VARCHAR(50) NOT NULL,
   CONSTRAINT fk_funcionario_voo FOREIGN KEY (funcionario_id) REFERENCES funcionario (funcionario_id),
   CONSTRAINT fk_voo FOREIGN KEY (voo_id) REFERENCES voo (voo_id)
);

-- Tabela de Passageiros por Voo
CREATE TABLE passageiro_voo (
   passageiro_voo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   passageiro_id     NUMBER NOT NULL,
   voo_id             NUMBER NOT NULL,
   assento           VARCHAR(10) NOT NULL,
   status_voo        VARCHAR(50) NOT NULL,
   CONSTRAINT fk_passageiro_voo_passageiro FOREIGN KEY (passageiro_id) REFERENCES passageiro (passageiro_id),
   CONSTRAINT fk_passageiro_voo_voo FOREIGN KEY (voo_id) REFERENCES voo (voo_id)
);

-- Tabela de Manutenção
CREATE TABLE manutencao (
   manutencao_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   aeronave_id      NUMBER NOT NULL,
   funcionario_id   NUMBER NOT NULL,
   data_manutencao  DATE NOT NULL,
   descricao        VARCHAR(255) NOT NULL,
   custo            NUMBER NOT NULL,
   CONSTRAINT fk_aeronave_manutencao FOREIGN KEY (aeronave_id) REFERENCES aeronave (aeronave_id),
   CONSTRAINT fk_funcionario_manutencao FOREIGN KEY (funcionario_id) REFERENCES funcionario (funcionario_id)
);



-- Passageiros em voos nacionais
SELECT DISTINCT
         p.nome,
         p.cpf,
         p.telefone,
         p.passaporte,
         v.numero_voo,
         origem.nome AS origem,
         destino.nome AS destino
    FROM passageiro p
    JOIN passageiro_voo pv ON p.passageiro_id = pv.passageiro_id
    JOIN voo v ON pv.VOO_ID = v.VOO_ID
    JOIN aeroporto origem ON v.ORIGEM_ID = origem.AEROPORTO_ID
    JOIN aeroporto destino ON v.DESTINO_ID = destino.AEROPORTO_ID
    WHERE origem.PAIS = 'Brasil' AND destino.PAIS = 'Brasil';




-- Passageiros em voos internacionais
SELECT DISTINCT
         p.nome,
         p.cpf,
         p.telefone,
         p.passaporte,
         v.numero_voo,
         origem.nome AS origem,
         destino.nome AS destino
    FROM passageiro p
      JOIN passageiro_voo pv ON p.passageiro_id = pv.passageiro_id
      JOIN voo v ON pv.VOO_ID = v.VOO_ID
   JOIN aeroporto origem ON v.ORIGEM_ID = origem.AEROPORTO_ID
   JOIN aeroporto destino ON v.DESTINO_ID = destino.AEROPORTO_ID
   WHERE origem.PAIS != 'Brasil' OR destino.PAIS != 'Brasil';

SELECT  
    f.nome AS Nome, 
    'Funcionario' AS Tipo, 
    v.numero_voo AS NumeroVoo, 
    v.data_partida AS DataPartida 
FROM  funcionario f 
JOIN  funcionario_voo fv ON f.funcionario_id = fv.funcionario_id 
JOIN   voo v ON fv.voo_id = v.voo_id 
UNION ALL 
   SELECT  
      p.nome AS Nome, 
      'Passageiro' AS Tipo, 
      v.numero_voo AS NumeroVoo, 
      v.data_partida AS DataPartida 
      FROM  
         passageiro p 
      JOIN  passageiro_voo pv ON p.passageiro_id = pv.passageiro_id 
      JOIN  voo v ON pv.voo_id = v.voo_id 
ORDER BY  
    DataPartida, Tipo, Nome;



SELECT v.numero_voo, ( 
      SELECT COUNT(*)   
      FROM funcionario_voo fv   
      WHERE fv.voo_id = v.voo_id  
    ) AS total_funcionarios  
FROM voo v;

SELECT p.nome, ( 
   SELECT COUNT(*)  
   FROM passageiro_voo pv  
   WHERE pv.passageiro_id = p.passageiro_id 
) AS total_voos 
FROM passageiro p;



-- Inserts para a Tabela de Aeronaves
INSERT INTO aeronave (modelo, fabricante, capacidade, status) VALUES ('Boeing 737', 'Boeing', 180, 'Operacional');
INSERT INTO aeronave (modelo, fabricante, capacidade, status) VALUES ('Airbus A320', 'Airbus', 160, 'Operacional');
INSERT INTO aeronave (modelo, fabricante, capacidade, status) VALUES ('Embraer E195', 'Embraer', 120, 'Em Manutenção');
INSERT INTO aeronave (modelo, fabricante, capacidade, status) VALUES ('Boeing 777', 'Boeing', 350, 'Operacional');
INSERT INTO aeronave (modelo, fabricante, capacidade, status) VALUES ('Airbus A350', 'Airbus', 300, 'Operacional');

-- Inserts para a Tabela de Passageiros
INSERT INTO passageiro (nome, cpf, telefone, passaporte) VALUES ('João Silva', '12345678901', '11987654321', 'AB1234567');
INSERT INTO passageiro (nome, cpf, telefone, passaporte) VALUES ('Maria Oliveira', '23456789012', '11876543210', 'CD2345678');
INSERT INTO passageiro (nome, cpf, telefone, passaporte) VALUES ('Carlos Souza', '34567890123', '11765432109', NULL);
INSERT INTO passageiro (nome, cpf, telefone, passaporte) VALUES ('Ana Pereira', '45678901234', '11654321098', 'EF3456789');
INSERT INTO passageiro (nome, cpf, telefone, passaporte) VALUES ('Paulo Santos', '56789012345', '11543210987', NULL);

-- Inserts para a Tabela de Funcionários
INSERT INTO funcionario (nome, cpf, cargo, setor) VALUES ('Carlos Henrique', '78901234567', 'Piloto', 'Avião');
INSERT INTO funcionario (nome, cpf, cargo, setor) VALUES ('Fernanda Lima', '89012345678', 'Comissária', 'Avião');
INSERT INTO funcionario (nome, cpf, cargo, setor) VALUES ('Eduardo Martins', '90123456789', 'Mecânico', 'Manutenção');
INSERT INTO funcionario (nome, cpf, cargo, setor) VALUES ('Cláudia Rocha', '01234567890', 'Agente de check-in', 'Aeroporto');
INSERT INTO funcionario (nome, cpf, cargo, setor) VALUES ('Ricardo Alves', '12345678901', 'Assistente de voo', 'Avião');

-- Inserts para a Tabela de Aeroportos
INSERT INTO aeroporto (nome, cidade, estado, pais) VALUES ('Aeroporto Internacional de São Paulo', 'São Paulo', 'São Paulo', 'Brasil');
INSERT INTO aeroporto (nome, cidade, estado, pais) VALUES ('Aeroporto de Guarulhos', 'São Paulo', 'São Paulo', 'Brasil');
INSERT INTO aeroporto (nome, cidade, estado, pais) VALUES ('Aeroporto Internacional de Lisboa', 'Lisboa', 'Lisboa', 'Portugal');
INSERT INTO aeroporto (nome, cidade, estado, pais) VALUES ('Aeroporto de Londres Heathrow', 'Londres', 'Inglaterra', 'Reino Unido');
INSERT INTO aeroporto (nome, cidade, estado, pais) VALUES ('Aeroporto Internacional de Miami', 'Miami', 'Flórida', 'Estados Unidos');

-- Inserts para a Tabela de Voos
INSERT INTO voo (numero_voo, aeronave_id, destino_id, origem_id, data_partida, data_chegada, status) 
VALUES ('SA123', 1, 1, 2, TO_DATE('2024-12-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO voo (numero_voo, aeronave_id, destino_id, origem_id, data_partida, data_chegada, status) 
VALUES ('IB456', 2, 3, 1, TO_DATE('2024-12-01 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-01 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO voo (numero_voo, aeronave_id, destino_id, origem_id, data_partida, data_chegada, status) 
VALUES ('LA789', 3, 4, 1, TO_DATE('2024-12-01 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-01 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);
INSERT INTO voo (numero_voo, aeronave_id, destino_id, origem_id, data_partida, data_chegada, status) 
VALUES ('AF321', 4, 5, 2, TO_DATE('2024-12-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-02 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO voo (numero_voo, aeronave_id, destino_id, origem_id, data_partida, data_chegada, status) 
VALUES ('AA654', 5, 2, 3, TO_DATE('2024-12-02 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-02 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

-- Inserts para a Tabela de Funcionários por Voo
INSERT INTO funcionario_voo (funcionario_id, voo_id, cargo_funcionario) VALUES (1, 1, 'Piloto');
INSERT INTO funcionario_voo (funcionario_id, voo_id, cargo_funcionario) VALUES (2, 1, 'Comissária');
INSERT INTO funcionario_voo (funcionario_id, voo_id, cargo_funcionario) VALUES (3, 2, 'Piloto');
INSERT INTO funcionario_voo (funcionario_id, voo_id, cargo_funcionario) VALUES (4, 3, 'Mecânico');
INSERT INTO funcionario_voo (funcionario_id, voo_id, cargo_funcionario) VALUES (5, 4, 'Agente de check-in');

-- Inserts para a Tabela de Passageiros por Voo
INSERT INTO passageiro_voo (passageiro_id, voo_id, assento, status_voo) VALUES (1, 1, '12A', 'Confirmado');
INSERT INTO passageiro_voo (passageiro_id, voo_id, assento, status_voo) VALUES (2, 2, '15B', 'Confirmado');
INSERT INTO passageiro_voo (passageiro_id, voo_id, assento, status_voo) VALUES (3, 3, '22C', 'Cancelado');
INSERT INTO passageiro_voo (passageiro_id, voo_id, assento, status_voo) VALUES (4, 4, '7D', 'Confirmado');
INSERT INTO passageiro_voo (passageiro_id, voo_id, assento, status_voo) VALUES (5, 5, '10E', 'Em Espera');

-- Inserts para a Tabela de Manutenção
INSERT INTO manutencao (aeronave_id, funcionario_id, data_manutencao, descricao, custo) 
VALUES (1, 3, TO_DATE('2024-11-15', 'YYYY-MM-DD'), 'Verificação do sistema de controle', 5000);
INSERT INTO manutencao (aeronave_id, funcionario_id, data_manutencao, descricao, custo) 
VALUES (2, 4, TO_DATE('2024-11-16', 'YYYY-MM-DD'), 'Troca de peças do motor', 7500);
INSERT INTO manutencao (aeronave_id, funcionario_id, data_manutencao, descricao, custo) 
VALUES (3, 5, TO_DATE('2024-11-17', 'YYYY-MM-DD'), 'Inspeção de segurança', 3000);
INSERT INTO manutencao (aeronave_id, funcionario_id, data_manutencao, descricao, custo) 
VALUES (4, 3, TO_DATE('2024-11-18', 'YYYY-MM-DD'), 'Calibração dos sensores', 2000);
INSERT INTO manutencao (aeronave_id, funcionario_id, data_manutencao, descricao, custo) 
VALUES (5, 4, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'Troca de pneus', 1500);
