CREATE USER airsystem IDENTIFIED BY airsystem
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CREATE SESSION,
        CREATE TABLE,
        CREATE SEQUENCE,
        CREATE VIEW,
        INSERT ANY TABLE,
        SELECT ANY TABLE,
        UPDATE ANY TABLE,
        DELETE ANY TABLE
TO airsystem;
